### ISSUE TITLE
keep jumplist

### ISSUE THREAD

**Issue by Konfekt** [rhysd/vim-textobj-anyblock#4]
The operator mode mappings, for example after `yq` if `omap q  <Plug>(textobj-anyblock-i)`, add a mark to the jump list. This seems rather unwanted than useful to me.

Checking the source code, I didn't see where the marking enters. Anyone else?

**Comment by rhysd** [comment]
Ah, good catch.
I didn't pay attention to jumplist.   I'll try to fix it. (I think `:keepjumps` helps to resolve.)

**Comment by Konfekt** [comment]
Ah, didn't know about keepjumps. Thanks for caring.

**Comment by Konfekt** [comment]
`:h jumplist` shows
```vim
You can explicitly add a jump by setting the ' mark with "m'".  
Note that calling setpos() does not do this.
```
