### ISSUE TITLE
Do nothing if not found

### ISSUE THREAD

**Issue by amerlyq** [rhysd/vim-textobj-anyblock#5]
Currently, if no block symbols was found at all, char under cursor will be deleted.
It's unwanted behaviour, as it contradicts expectations.
Better is to keep text unchanged -- as expected blocks non-existent.

**Comment by rhysd** [comment]
I can't reproduce it.
Could you tell me how to reproduce this issue? Especially, it is important that which operator you used.

**Comment by rhysd** [comment]
I could reproduce with `dib`.

**Comment by amerlyq** [comment]
You have forestall me by several seconds)

**Comment by rhysd** [comment]
Thanks! I understood.

**Comment by amerlyq** [comment]
By the way, is there any concrete reason, why you prefer to use region extension instead of ```searchpos()```?

**Comment by rhysd** [comment]
> By the way, is there any concrete reason, why you prefer to use region extension instead of searchpos()?

If we decide to implement like that, we must emulate Vim's original text objects such as `i(`, `i{`, and so on.  I thought it was better to avoid implementing such emulation and I implemented using Vim's original text object mappings.
